# See: https://github.com/artob/gitstamp-action
---
name: Gitstamp
on:
  push:
    branches:
      - master
jobs:
  gitstamp:
    runs-on: ubuntu-latest
    name: Timestamp commit with Gitstamp
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.2.0
      - name: Submit Gitstamp transaction
        uses: artob/gitstamp-action@v1
        with:
          wallet-key: ${{ secrets.GITSTAMP_KEYFILE }}
          commit-link: true
